version: "3"

services:
  db:
    image: "mysql:latest"
    restart: always
    environment:
      - "MYSQL_DATABASE=mysql"
      - "MYSQL_PASSWORD=docker"
      - "MYSQL_ROOT_PASSWORD=docker"
      - "MYSQL_USER=docker"
    ports:
      - "3306:3306"
    volumes:
      - ./db-dump/:/docker-entrypoint-initdb.d

  api:
    build: .
    ports:
      - "8080:8080"
    command: java -jar target/api-v1.0.0.jar
    depends_on:
      - db
